### ISSUE TITLE
Dual Oven - Lights

### ISSUE THREAD

**Issue by JibberSki** [simbaja/ha_gehome#121] opened 2022-10-18 22:31 UTC
Please add both lights to the ../devices/ge_oven.py.   For example if the oven has lower_oven then both lights (upper and lower) should be available.
`
if upper_light_availability is None or upper_light_availability.is_available:
                oven_entities.append(GeOvenLightLevelSelect(self, ErdCode.UPPER_OVEN_LIGHT, self._single_name(ErdCode.UPPER_OVEN_LIGHT)))
            if lower_light_availability is None or lower_light_availability.is_available:
                oven_entities.append(GeOvenLightLevelSelect(self, ErdCode.LOWER_OVEN_LIGHT))
`

**Comment by simbaja** [comment] 2022-10-25 21:29
I'm not sure what you're asking for in this issue, can you clarify?  The logic is there to add the lights if the light level is available, see: https://github.com/simbaja/ha_gehome/blob/c8d77120c9702690ce01e334220df986580d20c0/custom_components/ge_home/devices/oven.py#L77 and https://github.com/simbaja/ha_gehome/blob/c8d77120c9702690ce01e334220df986580d20c0/custom_components/ge_home/devices/oven.py#L91

The issue is that the GE appliances don't always report the lights properly.  If you have the ability to work through the lights showing up, can you perhaps submit a PR?

**Comment by ex-nerd** [comment] 2023-06-17 05:23
Also seeing this issue with my GE Cafe dual oven. Both lights show up in the official app but only the lower oven light in HA. Happy to help debug this if someone points me in the right direction.

Also weird that the light is showing up in HA is a `select` with `Off` and `High` settings rather than a `switch` or `light` type that just toggles on/off. Maybe other ovens have variable brightness?

**Comment by ex-nerd** [comment] 2023-06-17 06:00
I had a bunch more typed here but it turns out the fix was pretty simple, and ready in PR #174.

It looks like it really was just an oversight when adding all of the other upper oven configs to the top of that "if has a lower oven" block around line 77.

**Comment by ex-nerd** [comment] 2023-06-18 09:33
@JibberSki Looks like my patch was merged. Not sure when the next version will be published, but the 2-line change fixed it for me.

**Closed** 2023-07-30 22:38 UTC
