### ISSUE TITLE
Timeout errors, Attribute hass is None errors, and Mostly Unavailable

### ISSUE THREAD

**Issue by Snuffy2** [simbaja/ha_gehome#104] opened 2022-08-20 14:55 UTC
Have a new GE Washer and Dryer connected to SmartHQ. Since setting up the integration, it is throwing many errors and timing out. The integration seems to work occasionally, but mostly shows unavailable. The Washer and Dryer work fine in the SmartHQ iOS app. Happy to help debug further.

After a day or so, there are >1000 errors of:
- `RuntimeError: Attribute hass is None for <Entity GT345122N Laundry Machine State>`
- `RuntimeError: Attribute hass is None for <Entity HT135853G Laundry Machine State>`

Log from initial HA startup with Debug enabled:
[ge_home.log](https://github.com/simbaja/ha_gehome/files/9387355/ge_home.log)

**Comment by simbaja** [comment] 2022-08-23 13:26
Duplicate of #99

**Closed by simbaja** 2022-08-23 13:26 UTC
