### ISSUE TITLE
Errors after update to HA 2023.4.1

### ISSUE THREAD

**Issue by greg520820** [simbaja/ha_gehome#151] opened 2023-04-08 22:58 UTC
Getting the following error every 5 - 10 seconds since updating from HA 2023.3.6 to 2023.4.1.  Integration sensors do not update.  

Can still connect and control oven from GE app.

Logger: homeassistant
Source: helpers/entity.py:561
First occurred: 6:50:12 PM (21 occurrences)
Last logged: 6:51:37 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 269, in on_device_update
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 561, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <entity None=off>

**Comment by simbaja** [comment] 2023-04-23 02:00
Please use the dev version ([v0.6.6-dev1](https://github.com/simbaja/ha_gehome/releases/tag/v0.6.6-dev1) it should resolve the issue.  I haven't deployed that to production yet due to an auth issue reported that I'm still tracking down.

**Comment by Snuffy2** [comment] 2023-04-23 02:05
I've been running v0.6.6-dev1 since January. I started getting these errors again a couple of weeks ago.

**Comment by simbaja** [comment] 2023-04-23 04:01
@Snuffy2, any other information you can provide?  I don't have a washer/dryer, so hard to debug.  Can you set the logging level to debug in home assistant for this component and see if anything else pops out as odd?

**Comment by Snuffy2** [comment] 2023-04-23 15:37
Here is a link to ~30 min of HA logs with debug enabled. I see the error a lot but not a ton of other info about what may be triggering it. Happy to try other things.

https://0bin.net/paste/w9R5qec3#pNVU1U+2UdU-GZED54Z5le7uPOk4mDuU7fb48K+ogBa

**Comment by simbaja** [comment] 2023-04-23 17:28
If you disable the two laundry state entities, does the issue go away?  Or does it just show a different entity with an issue?

**Comment by Snuffy2** [comment] 2023-04-25 01:03
Yes, disabling the state entities makes the errors go away and the other entities seem to be reporting correctly.

**Comment by FuzzyMistborn** [comment] 2023-04-28 15:45
Running the latest version and I get this error as well.  Following the tip [here](https://github.com/simbaja/ha_gehome/issues/141#issuecomment-1523878984) if I disable the integration before reboot and then restart/enable the integration I don't get the error.

**Comment by simbaja** [comment] 2023-04-30 14:47
Can you try something, I think it's somehow related to duplicate entities:

1. Remove the integration
2. Reboot
3. Confirm there are no extra entities still around in some way
4. Add the integration back in
5. Reboot to confirm whether the issue is still present

@squirtbrnr, can you also try the same thing?

**Comment by squirtbrnr** [comment] 2023-05-01 13:42
> Can you try something, I think it's somehow related to duplicate entities:
> 
> 1. Remove the integration
> 2. Reboot
> 3. Confirm there are no extra entities still around in some way
> 4. Add the integration back in
> 5. Reboot to confirm whether the issue is still present
> 
> @squirtbrnr, can you also try the same thing?

I don't have any of the above reported errors in my logs.  I just enabled debug logging on the integration and also changed logging from error to debug on custom components in my config.  I'll report back if I see any of these logs.

However, your steps above are how I fix my issue when the integration goes unavailable periodically if I don't disable the integration before rebooting HA.

**Comment by raymercury** [comment] 2023-05-23 01:36
Having the same reported errors. Here are some detailed logs. Also, some errors mention about duplicate entities (cannot be added a second time to an entity platform).
Using SNMR160309Q oven.

[oven debug.txt](https://github.com/simbaja/ha_gehome/files/11538298/oven.debug.txt)

**Comment by robert-alfaro** [comment] 2023-05-23 19:30
I had a similar issue where this integration would just not  initialize. Turned out being loss of ipv6 address at my Comcast modem :unamused: ... renew/release ip made the gehome server reachable again.

**Comment by simbaja** [comment] 2023-06-04 23:13
@raymercury , can you fully remove the integration and re-add it?  You may need to manually clean-up the entities as well.

**Comment by raymercury** [comment] 2023-06-06 04:18
@simbaja
Steps I did:
1. Delete integration/device from HA:8123/config/integrations
2. Checked developer tools and entities for leftover entities (there were none)
3. Remove integration GE Home (SmartHQ) from HA:8123/hacs/integrations
4. Restart Home Assistant
----
5. Install integration GE Home (SmartHQ) from HA:8123/hacs/integrations
6. Restart Home Assistant
----
7. Add integration from HA:8123/config/integrations
8. Go through configuration and sign in.
9. Finish configuration which adds all oven entities again.
----
Result: No more error logs for this particular issue (for now).

**Comment by simbaja** [comment] 2023-07-30 20:50
Closing this issue, have pinned general troubleshooting steps, seems to be a re-install needed when this occurs.

**Closed by simbaja** 2023-07-30 20:50 UTC
