### ISSUE TITLE
Integration goes unavailable periodically every hour

### ISSUE THREAD

**Issue by squirtbrnr** [simbaja/ha_gehome#141] opened 2023-02-01 16:43 UTC
I've been using this integration for a while, but recently (past couple of weeks) the entities of the integration go unavailable for about 45 minutes once every hour.  I only have an oven, and control of it works, but even when I am using it, the integration will briefly go unavailable.  When I am in this long stretch of it being unavailable, I can disable/enable and reload the integration and it initializes again, but the entities don't always become available.  Sometimes it takes 2-3 reloads of the integration for it co become available again.  I checked the GE appliance app and it shows the oven as available and can be controlled during the time Home Assistant says it is unavailable.

![image](https://user-images.githubusercontent.com/35356217/216106596-ddc31176-2ae7-4523-afba-a8f47ec45ba5.png)

**Comment by squirtbrnr** [comment] 2023-02-01 20:41
After I disabled, then re-enabled the integration everything was fine for 1 hour after that.  Then it would be unavailable for 59:30 each hour and only available for 30 seconds.  There might be an account auth issue or too many API calls within an hour.

**Comment by squirtbrnr** [comment] 2023-02-13 04:55
this is definitely an authentication timeout.  I was able to delete the integration and add it back in and things were stable for a few days.  Then I needed to reboot HA and ever since then this integration goes unavailable every hour.  Now however, I have tried removing the integration and two things happen: 1) when I remove the integration, I cannot delete any of the entities and they are all stuck in the device/entity registry and 2) when I add the integration again it successfully connects to my account but no entities get added.  No logs show an error on reload.

**Comment by simbaja** [comment] 2023-02-16 04:22
That is so odd, it's been stable on multiple machines, what is your configuration?  The 1 hour timeout is actually probably the websocket connection, it terminates every hour and is refreshed.  Something seems to be preventing you from refreshing that connection.

**Comment by squirtbrnr** [comment] 2023-02-23 16:28
I got the integration and entities removed, but I had to brute force the devices and entities file in the `.storage` folder.  I have yet to re-add this integration again, but I have deleted it and re-downloaded it through HACS so I know I am running the latest release.  I have recently had a few other integrations behave weirdly or improperly which required removing them and reconfiguring them.  The common theme was all of these integrations with issues (entities going unavailable) have been configured for close to a couple years going back to HA versions in 2020/2021.

Will attempt to add the integration this weekend and see how it behaves.

**Comment by antokara** [comment] 2023-02-24 14:55
Same here. The washer becomes unavailable almost on a regular basis/schedule.

If I go through the smart HQ app, it shows it offline there as well. It really looks like my IP address or login gets throttled or something.

Also, this started the last 2 weeks or so. Previously, it was still happening but much less frequently and for smaller durations.

I guess That's the problem with devices that use 3rd party servers and aren't local... You can't beat z-wave/ZigBee/etc...

**Comment by squirtbrnr** [comment] 2023-02-26 06:08
If the SmartHQ app also shows it offline, that’s possibly a different issue than this. When my integration showed unavailable in HA, the app still showed the oven and everything was accessible. If your app shows your washer offline, go through the Wi-Fi troubleshooting for your washer. My oven had a Wi-Fi issue a couple years ago due to it being enclosed and a built in to the wall. Once I relocated a wireless access point things were better and it no longer was going offline. But there was also a bad few releases of firmware that crippled the internet connectivity which GE fixed as well.

as for my issue above, I’ve had the integration added again for 2 days and even did a few reboots of HA in there. So far it has not gone unavailable. I’ll keep monitoring it for the next few days.

**Comment by antokara** [comment] 2023-03-02 04:04
@squirtbrnr it's not always the case that the washer appears offline in the smart HQ app and unavailable in home assistant. It's just that there have been multiple times that it has happened but not the majority of the cases.

At things point, honestly, I'm giving up on this. I ordered a z-wave receptacle power monitor, that I'll use to know if the washer is operational or not, through the amps it uses... That will be without delays and without having to rely on GE's servers.

Would I prefer to have all the details of this integration? Sure. But I can't rely on this any more and I truly believe it's GE's servers to blame. But that's how it is with hosted proprietary services...

**Comment by squirtbrnr** [comment] 2023-03-03 02:44
@simbaja everything was working fine over the weekend and for most of this week.  Then today (Thursday 3/2, in fact just a few minutes ago) I upgraded my HA container from 2023.2.5 to 2023.3.1.  When everything came back up, this integration showed everything as unavailable except for the oven entity with temperature control (the one that shows up as a water heater).  I reloaded the integration and all entities are showing again.  I'll keep watching but this is where the integration would typically start to drop out once per hour.  I could always tell it would do so whenever on a restart the integration didn't successfully start up.

**Comment by squirtbrnr** [comment] 2023-03-04 13:05
I turned on some logging and my log is littered with this error every 30 seconds.  I believe there was a change in the async update in HA core recently because I saw a GitHub issue filed in another custom component I use.
```
2023-03-03 20:46:51.182 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 267, in on_device_update
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 552, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity SNSM026412Q Cook Mode>
```

**Comment by squirtbrnr** [comment] 2023-03-09 14:52
@simbaja I ran into this interesting scenario yesterday.  The integration had gone unavailable, so I deleted it.  My hope was to let it time out on the next attempt to authenticate and then a few hours later add the integration back in with a fresh account auth.  However, to my surprise, about 10 minutes after I had deleted the integration, the entities all showed up on my dashboard and were showing data.  The integration was completely gone from the settings/integrations and devices page, but the entities were still there and updating.  This only lasted maybe 5 minutes, then they were gone again.

**Comment by simbaja** [comment] 2023-04-23 04:28
@squirtbrnr , are you still experiencing this issue?

**Comment by squirtbrnr** [comment] 2023-04-23 14:29
@simbaja yes.  just ran into it again Friday.  If I reboot HA, the integration does not come back and all but one entity shows as unavailable.  I have to delete the integration, then re-add the integration after waiting an hour or so. If I try to re-authenticate and add the integration before it times out, then it will go unavailable again periodically.  My work-around is before I reboot HA, I disable the integration, then reboot, then re-enable the integration and everything is fine.

**Comment by squirtbrnr** [comment] 2023-04-26 18:38
Rebooted yesterday to apply the updated integration from HACs.  Still experiencing the integration going unavailable periodically. If I disable the integration before rebooting then re-enable it afterwards, everything is fine and the integration is stable.  If I forget to disable before rebooting, the integration is usually unavailable after startup.  If I remove the integration but don't reboot, the entities become available then go unavailable again periodically despite the integration being removed.  It's not until I reboot again that it is completely gone and I can re-authenticate with GE's servers.

**Comment by JakeCK** [comment] 2023-08-04 15:57
Do not know if this is related but I'm having the issue where upon restart of HA neither of my GE windows AC's are available. Restarting the integration after a restart gets all of the entities back but I'm unable to make any changes. If I try to change the mode or temperature it just goes back to what it was set to, however changes made from with in the HE app or on the device are reflected immediately. If I remove the account and sign back in all is well until the next HA restart. I've already completely uninstalled the integration from HACS and reinstalled still having the same issue. Been on going for several weeks now, and I believe it started after an update to HA. I also suspect it is an auth issue.

**Comment by simbaja** [comment] 2023-08-04 21:32
Do you have a log of the issue?

**Comment by JeffSteinbok** [comment] 2023-09-02 19:17
I'm seeing this too. Restarting HA fixed it. 

I had similar issues on an integration I wrote with websocket recreation being a pain. 

Let me know what logs to send.

**Comment by dylpicklee** [comment] 2023-09-26 19:00
i had this exact same issue with my ice machine. i rolled back to v6.6 and it stopped the problem.

**Comment by ziptbm** [comment] 2023-10-03 13:24
I'm seeing this now too.  I have three devices (Washer, Dryer, and Fridge).   It's been only in the last couple of days that I've noticed regular alerts about the devices being unavailable since I have automations built on the fridge and freezer temp in case the door gets accidentally left open.  I've been using the Washer and Dryer now for years (thank you for your contributions to this @simbaja !), however it's now becoming unreliable.  I've enabled debug logging and will share more once I gather more data, but please let me know what else would be helpful.   

I've confirmed through UniFi these devices are not losing WiFi connection and also via the SmartHQ app, so I've eliminated that as the culprit.  Here's a sample of what I'm seeing where the device is periodically becoming unavailable. 
<img width="578" alt="Screenshot 2023-10-03 at 09 21 54" src="https://github.com/simbaja/ha_gehome/assets/46136563/2b4967bb-5f4d-42bb-8a17-6e86fcfe0eac">

**Comment by soonerfan237** [comment] 2023-10-03 23:51
This is happening to me too. I have a washer and dryer and what's interesting is that they're not always unavailable at the same time. But they both follow the same cadence of being out for almost exactly one hour time blocks (1:00:25 to be exact).
<img width="666" alt="Screenshot 2023-10-03 at 6 48 43 PM" src="https://github.com/simbaja/ha_gehome/assets/11335516/200c9203-c6ba-4cef-b587-c312cebcf2bb">

**Comment by squirtbrnr** [comment] 2023-12-20 15:42
@simbaja I just installed v0.6.9-dev6 on HA 2023.12.3 and restarted.  The integration stayed connected and all entities for my oven were available after restart.  It has not gone unavailable yet but has only been up for about 20 minutes.

**Comment by simbaja** [comment] 2023-12-24 01:10
I'm going to close this assuming that the latest prerelease resolves this issue.  Please let me know if otherwise and I will reopen.

**Closed by simbaja** 2023-12-24 01:10 UTC

**Comment by ziptbm** [comment] 2023-12-26 17:28
> I'm going to close this assuming that the latest prerelease resolves this issue. Please let me know if otherwise and I will reopen.

@simbaja Do you still need folks to test this?  Or when is this fix scheduled to enter the main builds?
