### ISSUE TITLE
Feature Request: Monogram Gas Range (or Dual Fuel) - Addition of cooktop status (burner is on or off).

### ISSUE THREAD

**Issue by wardwolfram** [simbaja/ha_gehome#173] opened 2023-06-15 16:20 UTC
The Monogram gas or dual fuel ranges report if a burner is on/off within SmartHQ.  Great for one to understand if the range has been left on.

SmartHQ reports the cooktop burner status (for each burner), but the GEhome repository does not include this status. Would you please consider adding this reporting?  If there is a way I can assist, please reach out and am happy to do so.  Thanks!

**Comment by simbaja** [comment] 2023-06-17 13:12
Closing as a duplicate of #159, let's figure it out over there.  The support has potentially been added to the SDK, just need some people to help test to confirm.

**Closed by simbaja** 2023-06-17 13:12 UTC
