### ISSUE TITLE
Another 0.6.8 Issue (GE Smart Oven)

### ISSUE THREAD

**Issue by gitmesomepizza** [simbaja/ha_gehome#202] opened 2023-10-09 18:43 UTC
I'm having few issues with GE Home integration that started with 0.6.8 with my GE Smart Oven (Double)

- gehome occasionally stops updating some/all of the sensors (errors below)
- if the integration is reloaded, all sensors and controls seem to stop working (errors below)
- in both of these situations, restarting home assistant usually fixes it temporarily

### Related logs for "gehome occasionally stops updating some/all of the sensors":
```
Logger: homeassistant
Source: helpers/entity.py:756
First occurred: October 7, 2023 at 9:06:10 PM (6976 occurrences)
Last logged: 2:00:37 PM
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 280, in on_device_update
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 756, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <entity None=off>
```
When this happens, I can usually still turn on the oven via home assistant, but cannot turn it off (presumably since gehome doesn't know the oven is on since the relevant sensor won't update)

### Related logs for "if the integration is reloaded, all sensors and controls seem to stop working":
```
Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:507
Integration: Binary sensor ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
First occurred: 2:26:57 PM (1 occurrences)
Last logged: 2:26:57 PM
Error adding entities for domain binary_sensor with platform ge_home

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1025, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity binary_sensor.sngr068766q_lower_oven_remote_enabled cannot be added a second time to an entity platform
```
```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:507
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 2:26:57 PM (1 occurrences)
Last logged: 2:26:57 PM
Error adding entities for domain sensor with platform ge_home

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 189, in add_to_platform_start
    super().add_to_platform_start(hass, platform, parallel_updates)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1025, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.sngr068766q_lower_oven_cook_mode cannot be added a second time to an entity platform
```
```
Logger: homeassistant.components.water_heater
Source: helpers/entity_platform.py:507
Integration: Water Heater ([documentation](https://www.home-assistant.io/integrations/water_heater), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+water_heater%22))
First occurred: 2:26:57 PM (1 occurrences)
Last logged: 2:26:57 PM
Error adding entities for domain water_heater with platform ge_home

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1025, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity water_heater.sngr068766q_lower_oven cannot be added a second time to an entity platform
```
```
Logger: homeassistant
Source: helpers/entity.py:1025
First occurred: 2:26:57 PM (3 occurrences)
Last logged: 2:26:57 PM
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1025, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity binary_sensor.sngr068766q_lower_oven_remote_enabled cannot be added a second time to an entity platform
```

**Comment by claudermilk** [comment] 2023-10-12 13:18
I'm running into the same issue for both the oven and the hood.

**Comment by KyleStilkey** [comment] 2023-10-26 20:51
I'm getting similar issues but I have their Water Filter. Reloading the integration fixes it but every reboot I have to go and reload it to get function but I am also being loaded with lots off errors just like these ones.

```
Error adding entities for domain binary_sensor with platform ge_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 991, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity binary_sensor.fdpoek5u01973_wh_filter_manual_mode cannot be added a second time to an entity platform
```

```
Error adding entities for domain sensor with platform ge_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 215, in add_to_platform_start
    super().add_to_platform_start(hass, platform, parallel_updates)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 991, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.fdpoek5u01973_wh_filter_mode cannot be added a second time to an entity platform
```

```
Error adding entities for domain select with platform ge_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 991, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity select.fdpoek5u01973_wh_filter_position cannot be added a second time to an entity platform
```

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 991, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity binary_sensor.fdpoek5u01973_wh_filter_manual_mode cannot be added a second time to an entity platform
```

**Comment by claudermilk** [comment] 2023-11-09 15:01
FYI, this issue is worse. It loses connection to the GE appliances basically daily. If I reload the integration it will show the status of the entities, but I cannot control any of them (e.g., hood fan or light settings)--HA will change the displayed setting but nothing happens on the actual appliance. I've also gotten several notifications the integration needs to be reconfigured. If I restart HA, it actually loses connectivity again and I have to restart. At this point the integration is essentially nonfunctional for me. :(

Logs show a whole pile of errors, not sure why it's doing this:

Logger: homeassistant.components.select
Source: helpers/entity_platform.py:507
Integration: Select (documentation, issues)
First occurred: 6:56:06 AM (1 occurrences)
Last logged: 6:56:06 AM

Error adding entities for domain select with platform ge_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 991, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity select.ge_oven_light cannot be added a second time to an entity platform

Logger: homeassistant.components.water_heater
Source: helpers/entity_platform.py:507
Integration: Water Heater (documentation, issues)
First occurred: 6:56:06 AM (1 occurrences)
Last logged: 6:56:06 AM

Error adding entities for domain water_heater with platform ge_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 991, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity water_heater.ge_oven cannot be added a second time to an entity platform

Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:507
Integration: Switch (documentation, issues)
First occurred: 6:56:06 AM (1 occurrences)
Last logged: 6:56:06 AM

Error adding entities for domain switch with platform ge_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 991, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity switch.ge_oven_sabbath_mode cannot be added a second time to an entity platform

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:507
Integration: Sensor (documentation, issues)
First occurred: 6:56:06 AM (1 occurrences)
Last logged: 6:56:06 AM

Error adding entities for domain sensor with platform ge_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 215, in add_to_platform_start
    super().add_to_platform_start(hass, platform, parallel_updates)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 991, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.ge_oven_cook_mode cannot be added a second time to an entity platform

Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:507
Integration: Binary sensor (documentation, issues)
First occurred: 6:56:06 AM (1 occurrences)
Last logged: 6:56:06 AM

Error adding entities for domain binary_sensor with platform ge_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 563, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 991, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity binary_sensor.ge_oven_remote_enabled cannot be added a second time to an entity platform

This error originated from a custom integration.

Logger: slixmpp.stringprep
Source: custom_components/ge_home/update_coordinator.py:8
Integration: GE Home (documentation)
First occurred: 6:54:57 AM (1 occurrences)
Last logged: 6:54:57 AM

Using slower stringprep, consider compiling the faster cython/libidn one.

**Comment by MRobi1** [comment] 2023-11-15 22:33
Running into this same issue. 
Did any of you find a solution?

**Comment by shmulyeng** [comment] 2023-11-21 23:23
To those with this issue, do you have more than 1 appliance on the account?

**Comment by MRobi1** [comment] 2023-11-21 23:26
I only have the oven.

**Comment by gitmesomepizza** [comment] 2023-11-22 23:24
> To those with this issue, do you have more than 1 appliance on the account?

I only have the one oven on my account.

**Comment by KyleStilkey** [comment] 2023-11-23 21:32
I only have the water filter.

**Comment by simbaja** [comment] 2023-12-09 15:21
Can you all try 0.6.9-dev4 or above (the pre-release/beta branch)?  It might resolve the issues you are seeing.

**Comment by shmulyeng** [comment] 2023-12-10 00:15
It seems to be working for me. Thanks!

**Comment by gitmesomepizza** [comment] 2023-12-12 03:08
> Can you all try 0.6.9-dev4 or above (the pre-release/beta branch)? It might resolve the issues you are seeing.

Installed 0.6.9-dev6 today, and it has been working fine so far!

**Comment by claudermilk** [comment] 2023-12-12 15:25
Updated to the last dev version this one and dev3 have been much more stable so far.

**Comment by simbaja** [comment] 2023-12-24 01:06
I'm going to close this for now, assuming that the latest pre-release fixes it.  Please let me know if the issue is still present for others and I'll reopen.

**Closed by simbaja** 2023-12-24 01:06 UTC
