### ISSUE TITLE
'ClientConnection' object has no attribute 'closed'

### ISSUE THREAD

**Issue by VlastiBroucek** [simbaja/ha_gehome#306] opened 2024-11-17 22:24 UTC
Home Assistant

- Core: 2024.11.2
- Supervisor: 2024.11.2
- Operating System: 13.2
- Frontend: 20241106.2

GE Home (SmartHQ): v0.6.13

Repeatedly getting these:

```
Logger: gehomesdk.clients.base_client
Source: /usr/local/lib/python3.12/site-packages/gehomesdk/clients/base_client.py:141
First occurred: 17 November 2024 at 18:58:56 (13 occurrences)
Last logged: 08:40:54

'ClientConnection' object has no attribute 'closed'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/gehomesdk/clients/base_client.py", line 132, in async_run_client
    await self._async_run_client()
  File "/usr/local/lib/python3.12/site-packages/gehomesdk/clients/websocket_client.py", line 133, in _async_run_client
    await self._disconnect()
  File "/usr/local/lib/python3.12/site-packages/gehomesdk/clients/websocket_client.py", line 246, in _disconnect
    if self._socket and not self._socket.closed:
                            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'ClientConnection' object has no attribute 'closed'. Did you mean: 'close'?
```

**Comment by yestrdave** [comment] 2024-11-21 20:30
Similar
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/ge_home/update_coordinator.py:334
integration: GE Home (documentation)
First occurred: 3:28:07 PM (1 occurrences)
Last logged: 3:28:07 PM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 334, in on_device_initial_update
    if self.connected and self.client.available:
                          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gehomesdk/clients/websocket_client.py", line 59, in available
    return self._socket and not self._socket.closed
                                ^^^^^^^^^^^^^^^^^^^
AttributeError: 'ClientConnection' object has no attribute 'closed'. Did you mean: 'close'?

**Comment by Waank1** [comment] 2024-11-30 21:48
Home Assistant

Core - 2024.11.3
Supervisor - 2024.11.4
Operating System - 13.2
Frontend - 20241106.2

Getting the same error, here is the log.

Logger: gehomesdk.clients.base_client
Source: /usr/local/lib/python3.12/site-packages/gehomesdk/clients/base_client.py:141
First occurred: November 29, 2024 at 15:58:28 (20 occurrences)
Last logged: 15:05:06

'ClientConnection' object has no attribute 'closed'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/gehomesdk/clients/base_client.py", line 132, in async_run_client
    await self._async_run_client()
  File "/usr/local/lib/python3.12/site-packages/gehomesdk/clients/websocket_client.py", line 133, in _async_run_client
    await self._disconnect()
  File "/usr/local/lib/python3.12/site-packages/gehomesdk/clients/websocket_client.py", line 246, in _disconnect
    if self._socket and not self._socket.closed:
                            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'ClientConnection' object has no attribute 'closed'. Did you mean: 'close'?

**Comment by simbaja** [comment] 2024-12-01 02:35
Duplicate of #304, closing.

**Closed by simbaja** 2024-12-01 02:35 UTC
Labels: duplicate
