### ISSUE TITLE
GE Monogram Oven Shabbos Mode

### ISSUE THREAD

**Issue by abbachia** [simbaja/ha_gehome#148] opened 2023-03-23 03:23 UTC
doesn''t seem to do anything...set a switch on dashboard and when the switch is turned on it never seems to register on the oven and then goes off by itself about 10-20 seconds later

If i could get this to work it would be huge for me and family

had it tied to automation which obviously did not work but error log on automation is below, maybe it'll have a clude

Logger: homeassistant.components.automation.oven_test
Source: helpers/service.py:709
Integration: Automation (documentation, issues)
First occurred: 11:00:00 PM (4 occurrences)
Last logged: 11:00:36 PM

oven test: Error executing script. Unexpected error for device at pos 2: 'GeOven' object has no attribute 'async_turn_on'
While executing automation automation.oven_test
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 692, in _async_device_step
    await device_action.async_call_action_from_config(
  File "/usr/src/homeassistant/homeassistant/components/device_automation/action.py", line 76, in async_call_action_from_config
    await platform.async_call_action_from_config(hass, config, variables, context)
  File "/usr/src/homeassistant/homeassistant/components/water_heater/device_action.py", line 69, in async_call_action_from_config
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 709, in _handle_entity_call
    result = hass.async_run_job(partial(getattr(entity, func), **data))  # type: ignore[arg-type]
AttributeError: 'GeOven' object has no attribute 'async_turn_on'

**Comment by simbaja** [comment] 2023-04-23 04:23
I'm honestly not sure what the Sabbath mode switch does - it doesn't seem to work from what I've seen either.  However, looking at your error, it looks like you're trying to use the "turn_on" service, which doesn't exist for a water_heater (which is what I'm using to simulate an oven).  Try the "set_temperature" service instead, it should get you what you need: https://www.home-assistant.io/integrations/water_heater/

Hope this helps!

**Comment by abbachia** [comment] 2023-05-03 04:23
thank you for your response..

what Shabbos mode does is as follows.. it is designed for orthodox jews
(like myself) who have the custom not to do certain things on our sabbath
(pronounced Shabbos for us hence the name of the mode).  opening the door
ordinarily would trigger the light to go on and the oven would turn off
until the door is closed. turning lights on and off and turning the oven on
and off by opening and closing the door would therefore be problematic.  so
would setting the oven temp as well as turning the oven on or off

to accommodate the orthodox jewish community, GE (and other manufacturers)
include a shabbos mode which allows us to utilize the oven during our
sabbath if we set it before the sabbath begins.  once the sabbath mode is
turned on, we can open and close the oven door without triggering any
lights or temp/oven changes..
Before the sabbath begins on the oven we 1) initiate shabbath mode 2) set
the temp and 3) set the duration the oven stays on ( if we want the oven to
turn off by itself) 4) and then press start and voila we are in
shabbath mode.

issue is, its something that i/we need to remember to do before sabbath
starts (sundown on friday).  I was ecstatic to see that there was a home
assistant integration for the GE oven that included the ability to trigger
shabbath mode...my first through was that i could now automate the process
to go by itself.

If there is anything i can to to help you help me figure out how to get the
sabbath mode automated in HA it would be HUGE!!!

Thank you!

**Comment by simbaja** [comment] 2023-05-03 14:16
Sure, absolutely can help make this work.  I think the first thing we should do here is go to over to the SDK project (https://github.com/simbaja/gehome) and get that installed and start up the application there.  Once that's running, if you can use the official app to trigger the Shabbos mode, we might be able to see what it does on your device (presumably the same for all devices) and then can hopefully make some changes to get it working.

**Comment by abbachia** [comment] 2023-05-04 13:59
Great...so the GE Home integration linked above is different than
https://github.com/simbaja/ha_gehome" ??

**Comment by simbaja** [comment] 2023-05-04 14:02
Yes, it's the underlying SDK that provides the functionality for the Home Assistant integration

**Comment by abbachia** [comment] 2023-05-07 19:42
thanks...not totally familiar with PIP install...all other integration i
installed was either directly on the front end of HA or a custom repository
in HACS....how does this work?

**Comment by simbaja** [comment] 2023-06-05 00:19
So, I looked into the Shabbos mode on my oven.  The switch itself works from what I see (I flip it on, and the oven goes into Shabbos mode and turns off most of the controls).  The issue is that it also disables remote control in this mode, so after Shabbos mode is activated, there's nothing you can do remotely.  So, it seems you can set it (maybe not with your model??) but not much can be done after.  I did read my manual (didn't know how to get out of Shabbos mode), and noticed that there's something that they sell that automates this called the Shabbos Keeper: https://www.zmantechnologies.com/.  

Let me know if there's anything else I can do here, but I think I'm at a dead end unless you see any other avenues for me to go down.

**Comment by simbaja** [comment] 2023-07-30 20:51
I think I'm at a dead end here, closing for now, but please let me know if there's something else I can try.

**Closed by simbaja** 2023-07-30 20:51 UTC
