### ISSUE TITLE
Upgrade to Home Assistant 2022.8.0 may break integration?

### ISSUE THREAD

**Issue by stephenjamieson** [simbaja/ha_gehome#99] opened 2022-08-03 22:15 UTC
After upgrading to HA 2022.8.0, I'm seeing the following issues:

 async_setup errors

```
Logger: homeassistant.config_entries
Source: custom_components/ge_home/update_coordinator.py:174
Integration: GE Home (documentation)
First occurred: 2:39:53 PM (1 occurrences)
Last logged: 2:39:53 PM

Error setting up entry <email address> for ge_home
Traceback (most recent call last):
  File "/homeassistant/custom_components/ge_home/update_coordinator.py", line 172, in async_setup
    await self.initialization_future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hass/homeassistant/lib/python3.10/site-packages/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/homeassistant/custom_components/ge_home/__init__.py", line 45, in async_setup_entry
    if not await coordinator.async_setup():
  File "/homeassistant/custom_components/ge_home/update_coordinator.py", line 174, in async_setup
    raise HaCannotConnect("Initialization timed out")
custom_components.ge_home.exceptions.HaCannotConnect: Initialization timed out
```

Repeating messages regarding "Attribute hass is None for":

```
RuntimeError: Attribute hass is None for <Entity R319139N Laundry Machine State>
2022-08-03 22:09:16.099 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity ZR158981G Laundry Machine State>
```

~~A message in the logs regarding use of deprecated methods:~~ fixed in dev

```
2022-08-03 20:17:58.788 WARNING (MainThread) [homeassistant.components.number] custom_components.ge_home.entities.common.ge_erd_number::GeErdNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
```

I switched to the latest dev in hacs to see, but same issues on  `v0.6.3-dev3`

**Comment by pcsmith811** [comment] 2022-08-04 01:15
I also am seeing this issue after updating to 2022.8.0:

Logger: homeassistant
Source: helpers/entity.py:525
First occurred: 4:25:21 PM (1016 occurrences)
Last logged: 6:12:33 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 267, in on_device_update
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 525, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity D828C90B6750 Laundry Machine State: Off>

**Comment by simbaja** [comment] 2022-08-04 03:06
I haven't upgraded to 2022.8.0 yet, but I'll try to look into it over the weekend and see what I can find.

**Comment by simbaja** [comment] 2022-08-07 14:36
I've updated to 2022.8.0 and it seems to be working for me, so I'll probably need a little more information from you both to track down any issues.  Can you turn debugging on in home assistant and restart so it generates logs from startup through the error?


> Error setting up entry <email address> for ge_home
> Traceback (most recent call last):
>   File "/homeassistant/custom_components/ge_home/update_coordinator.py", line 172, in async_setup
>     await self.initialization_future
> asyncio.exceptions.CancelledError

This generally is a connection error - I haven't gotten around to fixing this yet, but if it can't connect the first time it tries, it may kill the integration (future disconnects/reconnects are ok).  Can you try restarting HA and see if the issue is consistent?

@pcsmith811, can you also try the dev (0.6.3-dev3) release to see if it resolves your issue?

**Comment by JRoc1212** [comment] 2022-08-08 01:37
@simbaja I am also experiencing the same issue after upgrading to HA Core 2022.8.2. I tried updating to 0.6.3-dev3 release and same result. I also tried rebooting the host and no luck. Here are the logs:

```
2022-08-07 20:25:47.486 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ge_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-07 20:26:21.778 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform ge_home is taking over 10 seconds.
2022-08-07 20:26:21.806 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform ge_home is taking over 10 seconds.
2022-08-07 20:26:21.809 WARNING (MainThread) [homeassistant.components.light] Setup of light platform ge_home is taking over 10 seconds.
2022-08-07 20:26:21.811 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform ge_home is taking over 10 seconds.
2022-08-07 20:26:21.813 WARNING (MainThread) [homeassistant.components.water_heater] Setup of water_heater platform ge_home is taking over 10 seconds.
2022-08-07 20:26:21.815 WARNING (MainThread) [homeassistant.components.select] Setup of select platform ge_home is taking over 10 seconds.
2022-08-07 20:26:21.817 WARNING (MainThread) [homeassistant.components.climate] Setup of climate platform ge_home is taking over 10 seconds.
2022-08-07 20:26:21.819 WARNING (MainThread) [homeassistant.components.button] Setup of button platform ge_home is taking over 10 seconds.
2022-08-07 20:26:21.821 WARNING (MainThread) [homeassistant.components.number] Setup of number platform ge_home is taking over 10 seconds.
2022-08-07 20:26:35.394 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry <email> for ge_home
File "/config/custom_components/ge_home/update_coordinator.py", line 172, in async_setup
File "/config/custom_components/ge_home/__init__.py", line 45, in async_setup_entry
File "/config/custom_components/ge_home/update_coordinator.py", line 174, in async_setup
custom_components.ge_home.exceptions.HaCannotConnect: Initialization timed out
2022-08-07 20:26:36.692 ERROR (MainThread) [homeassistant.components.binary_sensor] Setup of platform ge_home is taking longer than 60 seconds. Startup will proceed without waiting any longer.
2022-08-07 20:26:36.695 ERROR (MainThread) [homeassistant.components.sensor] Setup of platform ge_home is taking longer than 60 seconds. Startup will proceed without waiting any longer.
2022-08-07 20:26:36.696 ERROR (MainThread) [homeassistant.components.light] Setup of platform ge_home is taking longer than 60 seconds. Startup will proceed without waiting any longer.
2022-08-07 20:26:36.697 ERROR (MainThread) [homeassistant.components.switch] Setup of platform ge_home is taking longer than 60 seconds. Startup will proceed without waiting any longer.
2022-08-07 20:26:36.698 ERROR (MainThread) [homeassistant.components.water_heater] Setup of platform ge_home is taking longer than 60 seconds. Startup will proceed without waiting any longer.
2022-08-07 20:26:36.698 ERROR (MainThread) [homeassistant.components.select] Setup of platform ge_home is taking longer than 60 seconds. Startup will proceed without waiting any longer.
2022-08-07 20:26:36.699 ERROR (MainThread) [homeassistant.components.climate] Setup of platform ge_home is taking longer than 60 seconds. Startup will proceed without waiting any longer.
2022-08-07 20:26:36.700 ERROR (MainThread) [homeassistant.components.button] Setup of platform ge_home is taking longer than 60 seconds. Startup will proceed without waiting any longer.
2022-08-07 20:26:36.701 ERROR (MainThread) [homeassistant.components.number] Setup of platform ge_home is taking longer than 60 seconds. Startup will proceed without waiting any longer.
File "/config/custom_components/ge_home/update_coordinator.py", line 268, in on_device_update
File "/config/custom_components/ge_home/update_coordinator.py", line 268, in on_device_update
```

**Comment by JRoc1212** [comment] 2022-08-08 01:47
@simbaja @stephenjamieson @pcsmith811 

FYI disabling and then enabling the GE Home Integration in the 'Devices & Services' section of the Settings brought everything back online.

**Comment by simbaja** [comment] 2022-08-08 13:12
Thanks @JRoc1212.  @stephenjamieson, @pcsmith811: can you confirm disabling/enabling works for you as well?   All of these logs are pointing at a timeout when first setting up the integration.  Perhaps HA changed the order in which they do things and it's not getting done in time.  I can certainly increase the timeout, but that may just hide an underlying issue.  

I didn't want to have to implement dynamic entities, but it may be required to get the integration to work reliably.  That'll take a while, unfortunately.  Hopefully the stopgap works for you all in the meantime.

**Comment by pgenera** [comment] 2022-08-08 13:46
I run HA on a particularly overloaded machine, and it definitely looks like
timeouts to me as well, but disabling and enabling the integration does not
resolves things for me.

**Comment by pcsmith811** [comment] 2022-08-08 17:39
> Thanks @JRoc1212. @stephenjamieson, @pcsmith811: can you confirm disabling/enabling works for you as well? All of these logs are pointing at a timeout when first setting up the integration. Perhaps HA changed the order in which they do things and it's not getting done in time. I can certainly increase the timeout, but that may just hide an underlying issue.
> 
> I didn't want to have to implement dynamic entities, but it may be required to get the integration to work reliably. That'll take a while, unfortunately. Hopefully the stopgap works for you all in the meantime.

Reloading the integration gets rid of the timeout errors on the integrations and the red ! but the entities don't seem to update... these are the errors I am getting after a reload:

Logger: homeassistant
Source: helpers/entity.py:525
First occurred: 9:41:44 AM (180 occurrences)
Last logged: 10:12:45 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 267, in on_device_update
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 525, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity D828C90B6750 Laundry Machine State: Off>

9:41am was when I restarted HA

Interestingly enough though - disabling and re-enabling the integration appear to fix things... until a restart.   I'm using 0.6.1 as I am not even sure how to use the beta version.

**Comment by pcsmith811** [comment] 2022-08-08 21:31
I spoke too soon - none of the entities are actually updating and now I have a lot more errors:

Logger: homeassistant
Source: helpers/entity.py:525
First occurred: 9:41:44 AM (5459 occurrences)
Last logged: 2:30:21 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 267, in on_device_update
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 525, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity D828C90B6750 Laundry Machine State: Off>

**Comment by JRoc1212** [comment] 2022-08-09 03:39
Same happened to me as well, I just noticed today all the GE sensors showed "Unresponsive". Disabling and Enabling did not work this time...however selecting Reload seemed to work to get the GE sensors to report proper status.

Logs:
```
Logger: homeassistant
Source: helpers/entity.py:525
First occurred: August 7, 2022 at 11:09:11 PM (19293 occurrences)
Last logged: 10:28:06 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 268, in on_device_update
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 525, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity SNSM078867Q Sabbath Mode: off>
```

```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:157
First occurred: August 7, 2022 at 11:25:18 PM (18 occurrences)
Last logged: 10:27:52 PM

Error setting up entry <email> for select
Error setting up entry <email> for climate
Error setting up entry <email> for light
Error setting up entry <email> for button
Error setting up entry <email> for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 167, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 157, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```

**Comment by JRoc1212** [comment] 2022-08-13 07:30
I updated HA core to 2022.8.4 and was expecting to have to reload the this integration after the system restart…but happy to report that it started successfully on its own. Perhaps the HA team fixed something in the core code.

**Comment by simbaja** [comment] 2022-08-13 15:15
Thanks @JRoc1212. @stephenjamieson, @pcsmith811, @pgenera, does 2022.8.4 resolve the issue for you as well?

**Comment by pcsmith811** [comment] 2022-08-13 17:12
Appears to have resolved it for me as well - thank you!

**Comment by stephenjamieson** [comment] 2022-08-13 21:14
Same, looks good 👍

**Comment by pgenera** [comment] 2022-08-13 22:21
Unfortunately still broken for me and my underpowered system on 2022.8.4 :(

**Comment by jamagic** [comment] 2022-08-14 01:04
Upgrading to 2022.8.4, uninstalling Integration, reboot, reinstall Integration, reboot got it working for me again. However, I now have this in the logs:

```
Logger: homeassistant.components.number
Source: components/number/__init__.py:231
Integration: Number (documentation, issues)
First occurred: 2:27:08 PM (3 occurrences)
Last logged: 2:27:09 PM

custom_components.ge_home.entities.common.ge_erd_number::GeErdNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
custom_components.ge_home.entities.ccm.ge_ccm_brew_temperature::GeCcmBrewTemperatureNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
custom_components.ge_home.entities.ccm.ge_ccm_brew_cups::GeCcmBrewCupsNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
```

**Comment by simbaja** [comment] 2022-08-14 01:29
That one is resolved in the newest dev release, so you should be good.  I think I still might need to rework initialization, seems there still might be some issues with some installations.

**Comment by JRoc1212** [comment] 2022-08-22 15:22
FYI upgrading to 2022.8.6 core brought back the previous issue. Downgraded and everything is working again. 

Unless you need a specific new feature of a core update, I would hold off on upgrading. This is the approach I'm taking now. I've had nothing but issues with every core update since 2022.7.7 across multiple integrations, including those included with HA as well as the system itself.

**Comment by simbaja** [comment] 2022-08-23 13:26
I'm going to keep this one open until I rewrite the initialization.  Something changed in 2022.8.x, and a lot more people are seeing this issue.  Hopefully, we can get it fixed up.

**Comment by ssneisius** [comment] 2022-08-29 16:24
Getting similar errors after fresh install in a pretty clean set up.

Logger: homeassistant.components.number
Source: components/number/__init__.py:231
Integration: Number ([documentation](https://www.home-assistant.io/integrations/number), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+number%22))
First occurred: 11:23:55 AM (3 occurrences)
Last logged: 11:23:55 AM

custom_components.ge_home.entities.common.ge_erd_number::GeErdNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
custom_components.ge_home.entities.ccm.ge_ccm_brew_temperature::GeCcmBrewTemperatureNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
custom_components.ge_home.entities.ccm.ge_ccm_brew_cups::GeCcmBrewCupsNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.

I had the "deprecated methods on an instance of NumberEntity" on another integration and it was fixed by adding native_ to the values as in this post (https://github.com/rospogrigio/localtuya/pull/944/files).

Also getting this error,

This error originated from a custom integration.

Logger: slixmpp.stringprep
Source: custom_components/ge_home/update_coordinator.py:8
Integration: GE Home (documentation)
First occurred: 11:23:55 AM (1 occurrences)
Last logged: 11:23:55 AM

Using slower stringprep, consider compiling the faster cython/libidn one.

**Comment by simbaja** [comment] 2022-08-29 16:26
Use the dev version, it's resolved there

**Comment by ssneisius** [comment] 2022-08-29 16:36
I am pretty new to Home Assistant and have not used any dev versions, I will try to fumble my way through getting it updated, I assume I use dev3

**Comment by ssneisius** [comment] 2022-08-29 16:44
Thanks!

**Comment by JRoc1212** [comment] 2022-08-30 18:00
Had to update HA for other integrations to work and found out you still need to reload and/or disable+enable this integration to get it working after a restart. I'm on v0.6.3-dev3.

Home Assistant 2022.8.7
Supervisor 2022.08.5
Operating System 8.5
Frontend 20220802.0 - latest

**Comment by ssneisius** [comment] 2022-08-30 18:04
I just removed it and getting ready to load it again.

Home Assistant 2022.8.7
Supervisor 2022.08.5
Operating System 8.5
Frontend 20220802.0 - latest

**Comment by ssneisius** [comment] 2022-08-30 19:34
Installed and working but I still get an error in the log, Seems to be working well...

This error originated from a custom integration.

Logger: slixmpp.stringprep
Source: custom_components/ge_home/update_coordinator.py:8
Integration: GE Home (documentation)
First occurred: 3:25:44 PM (1 occurrences)
Last logged: 3:25:44 PM

Using slower stringprep, consider compiling the faster cython/libidn one.

**Comment by simbaja** [comment] 2022-08-30 19:35
Unless it's an error or something isn't working, ignore it.

**Comment by Snuffy2** [comment] 2022-09-01 21:14
I upgraded to v0.6.3-dev3 a couple of days ago and I seem to be still having the same issues as before. I can open a new issue, but it's the same errors as above and in #104 

When the Washer or Dryer become unavailable, I can go to Integrations and select Reload. About 30-50% of the time it will then reconnect, however, it will then become unavailable <60 min later.

I doubt this log has the right info to actually troubleshoot, but look at the sheer number of errors it is throwing in <10 seconds:
[home-assistant.log](https://github.com/simbaja/ha_gehome/files/9473457/home-assistant.log)

<img width="835" alt="2022-09-01_17-04-26 152" src="https://user-images.githubusercontent.com/6526076/188013137-125252c8-83fe-4799-8f20-472a86fc899e.png">

Please let me know what I can do to help troubleshoot further.

**Comment by simbaja** [comment] 2022-09-05 20:13
Can you guys try 0.6.5-dev1 and let me know if it works better for you?

**Comment by pgenera** [comment] 2022-09-05 21:12
so far so good, it's definitely working for me now!

**Comment by ssneisius** [comment] 2022-09-06 15:00
It is working after updating through HACS but I do get errors on restart and reload, below is the reload errors. They appear to be the same error but shows twice on every restart.

Logger: homeassistant.components.binary_sensor
Source: helpers/entity.py:745
Integration: Binary sensor (documentation, issues)
First occurred: 10:56:40 AM (1 occurrences)
Last logged: 10:56:40 AM

Error adding entities for domain binary_sensor with platform ge_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 468, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 745, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity binary_sensor.rr303387n_laundry_end_of_cycle cannot be added a second time to an entity platform

Logger: homeassistant.components.sensor
Source: helpers/entity.py:745
Integration: Sensor (documentation, issues)
First occurred: 10:56:40 AM (1 occurrences)
Last logged: 10:56:40 AM

Error adding entities for domain sensor with platform ge_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 468, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 745, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.rr303387n_laundry_machine_state cannot be added a second time to an entity platform

Still have the

**Comment by Snuffy2** [comment] 2022-09-08 20:28
> Can you guys try 0.6.5-dev1 and let me know if it works better for you?

Installed it ~3d ago and it is working much, much better!! It has reliably loaded with each HA restart and I haven't see the status become unavailable at all while HA is up. 

@simbaja thank you for all of your work on this!

I am getting this warning and error on HA restart but they don't seem to be affecting functionality:
```
2022-09-08 15:31:36.769 WARNING (MainThread) [slixmpp.stringprep] Using slower stringprep, consider compiling the faster cython/libidn one.
2022-09-08 15:31:51.584 ERROR (MainThread) [gehomesdk.clients.websocket_client] Unknown error reading socket
```

**Comment by ssneisius** [comment] 2022-09-09 11:46
After the latest updates, seems to be working fine and reporting correctly on my washer and dryer which is the only two units I have connected.

Home Assistant 2022.9.1
Supervisor 2022.08.6
Operating System 8.5
Frontend 20220907.0 - latest

I have the following error on start up,

This error originated from a custom integration.

Logger: slixmpp.stringprep
Source: custom_components/ge_home/update_coordinator.py:8
Integration: GE Home (documentation)
First occurred: 7:38:50 AM (1 occurrences)
Last logged: 7:38:50 AM

Using slower stringprep, consider compiling the faster cython/libidn one.


I have two errors on reload;

Logger: homeassistant.components.sensor
Source: helpers/entity.py:746
Integration: Sensor (documentation, issues)
First occurred: 7:31:47 AM (1 occurrences)
Last logged: 7:31:47 AM

Error adding entities for domain sensor with platform ge_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 468, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.fr143600g_laundry_machine_state cannot be added a second time to an entity platform

and,

Logger: homeassistant.components.binary_sensor
Source: helpers/entity.py:746
Integration: Binary sensor (documentation, issues)
First occurred: 7:31:47 AM (1 occurrences)
Last logged: 7:31:47 AM

Error adding entities for domain binary_sensor with platform ge_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 468, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity binary_sensor.fr143600g_laundry_end_of_cycle cannot be added a second time to an entity platform

**Comment by simbaja** [comment] 2022-09-17 15:26
@ssneisius , can you try 0.6.5-dev2 and let me know if the errors go away?  the stringprep one will remain, but that's just a warning.

**Comment by ssneisius** [comment] 2022-09-17 16:27
Done, on startup, only the stringprep remains. On reload, I still get these
two errors below. I am new to Python and Home Assistant but I had a
similar issue with the Aladdin integration where it was trying to load the
same device twice and this was corrected with a spacing issue in the code.

Logger: homeassistant.components.sensor
Source: helpers/entity.py:746
Integration: Sensor (documentation, issues)
First occurred: 12:22:13 PM (1 occurrences)
Last logged: 12:22:13 PM

Error adding entities for domain sensor with platform ge_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py",
line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py",
line 484, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746,
in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity
sensor.rr303387n_laundry_machine_state cannot be added a second time to an
entity platform

Logger: homeassistant.components.binary_sensor
Source: helpers/entity.py:746
Integration: Binary sensor (documentation, issues)
First occurred: 12:22:13 PM (1 occurrences)
Last logged: 12:22:13 PM

Error adding entities for domain binary_sensor with platform ge_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py",
line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py",
line 484, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746,
in add_to_platform_start
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity
binary_sensor.rr303387n_laundry_end_of_cycle cannot be added a second time
to an entity platform

**Comment by amorabito** [comment] 2022-09-24 13:20
I updated to HA 2022.9.6 (think it’s the latest)
Having similar issue but is intermittent it seems. Sometimes it starts up and works, other times I get Timeout in startup. Can usually get it back with Delete/Re-Install, this morning a Disable/Enable/Reload worked to get entities back from ‘Restored’.

Log:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/ge_home/update_coordinator.py:174 
Integration: GE Home (documentation) 
First occurred: 1:05:56 AM (1 occurrences) 
Last logged: 1:05:56 AM

Error setting up entry <email omitted> for ge_home
Traceback (most recent call last):
  File "/config/custom_components/ge_home/update_coordinator.py", line 172, in async_setup
    await self.initialization_future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ge_home/__init__.py", line 45, in async_setup_entry
    if not await coordinator.async_setup():
  File "/config/custom_components/ge_home/update_coordinator.py", line 174, in async_setup
    raise HaCannotConnect("Initialization timed out")
custom_components.ge_home.exceptions.HaCannotConnect: Initialization timed out


And these logs for sensors:


Logger: homeassistant.components.select
Source: helpers/entity_platform.py:253 
Integration: Select (documentation, issues) 
First occurred: 1:05:56 AM (1 occurrences) 
Last logged: 1:05:56 AM

Setup of platform ge_home is taking longer than 60 seconds. Startup will proceed without waiting any longer.

**Comment by simbaja** [comment] 2022-09-24 13:27
Try the prerelease version, it should solve this issue.

**Comment by amorabito** [comment] 2022-09-25 16:50
@simbaja worked perfect thank you!

**Closed** 2022-10-16 14:44 UTC
