### ISSUE TITLE
Error in cooktop status for CGY366P2T1S1

### ISSUE THREAD

**Issue by EnochPrime** [simbaja/ha_gehome#201] opened 2023-10-06 17:27 UTC
I receive the following error with Home Assistant 2023.10.0

Device: Café™ 36" Smart All-Gas Commercial-Style Range with 6 Burners (Natural Gas)
Model: CGY366P2T1S1
Firmware: Appliance=2.0.28.62/Wifi=0.2.11.62

```
Logger: gehomesdk.erd.converters.oven.cooktop_status_ext_converter
Source: /usr/local/lib/python3.11/site-packages/gehomesdk/erd/converters/oven/cooktop_status_ext_converter.py:32
First occurred: October 4, 2023 at 21:04:33 (4836 occurrences)
Last logged: 13:25:11

Could not convert cooktop status.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gehomesdk/erd/converters/oven/cooktop_status_ext_converter.py", line 27, in erd_decode
    if(any(x.on for x in burners)):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gehomesdk/erd/converters/oven/cooktop_status_ext_converter.py", line 27, in <genexpr>
    if(any(x.on for x in burners)):
           ^^^^
AttributeError: 'str' object has no attribute 'on'
```

**Comment by leonine0** [comment] 2023-11-25 15:46
Seems to be duplicate of https://github.com/simbaja/ha_gehome/issues/159
I submitted a patch for review

**Comment by EnochPrime** [comment] 2023-11-25 16:25
> I submitted a patch for review

I already submitted https://github.com/simbaja/gehome/pull/59 to fix this issue.

**Comment by simbaja** [comment] 2023-12-09 15:39
Closing in favor of moving discussion to #159

**Closed** 2023-12-09 15:49 UTC
